apiVersion: v1
kind: Secret
metadata:
  name: sgfv-secrets
type: Opaque
stringData:
  jwt-secret: {{ .Values.global.jwtSecret | quote }}
  db-password: {{ .Values.postgres.password | quote }}
  keycloak-admin-password: {{ .Values.keycloak.adminPassword | quote }}
